# Generated by Django 5.2 on 2025-05-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'women'), ('Kids', 'Kids')], default='Unisex', max_length=10),
        ),
    ]
