# Generated by Django 5.2 on 2025-05-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0004_category_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
    ]
