# Generated by Django 5.2 on 2025-05-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0006_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
